# Generated by Django 3.2.9 on 2022-03-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_alter_post_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myblog.catagory'),
        ),
    ]
