# Generated by Django 3.2.9 on 2022-03-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_post_catagory2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='catagory',
        ),
    ]
