# Generated by Django 3.2.9 on 2022-04-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_post_hader_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hader_image1',
            field=models.ImageField(blank=True, null=True, upload_to='Image/'),
        ),
    ]
