# Generated by Django 3.2.9 on 2022-04-29 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_post_hader_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hader_image1',
        ),
    ]
